#!/usr/bin/env bash
# Transfer a file from client to server
# Example: ./0-transfer_file some_page.html 35.237.54.178 ubuntu ~/.ssh/holberton

if [ $# -eq 4 ]
then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
