#!/usr/bin/env bash
# Pings an IP address passed as an argument
# Accepts a string as an argument
# Displays "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" if no argument
# Pings the IP 5 times

if [ ! -z "$1" ]
then
	ping "$1" -c5 
else
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
fi
