#!/usr/bin/env bash
# Runs 4-to_infinity_and_beyond and and displays "I am invincible!!!" when
# receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM 
while true
do
	echo "To infinity and beyond"
	sleep 2
done
