#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times with "Hi" on the 9th

i=0
while [ $i -lt 10 ]
do
	echo "Holberton School" 
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	(( ++i ))
done
