#!/usr/bin/env bash
# Loops from 1 to 10
# Display "bad luck" for 4th loop iteration
# Display "good luck" for 8th loop iteration
# Display "Holberton School" for other iterations

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School" 
	fi
	(( ++i ))
done
