#!/usr/bin/env bash
# Makes nginx run as nginx user

pkill apache2
echo "
user nginx;" >> /etc/nginx/nginx.conf
sed -i 's/\blisten 80\b/&80/' /etc/nginx/sites-available/default
sed -i 's/\blisten \[::\]:80\b/&80/' /etc/nginx/sites-available/default
service nginx restart
